name: house_organizer
description: "Group-Home Task Organizer – a comprehensive task and chore management app for group homes"
publish_to: 'none'
version: 1.0.0+1

environment:
  # Dart 3.8 ships with Flutter 3.32. Update the constraints so that
  # dev‑dependencies (freezed, build_runner, etc.) resolve correctly.
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter

  # State management
  flutter_riverpod: ^2.5.1
  riverpod: ^2.5.1

  # Firebase – versions that require Dart ≥3.2 and Flutter ≥3.3
  firebase_core: ^4.1.0
  cloud_firestore: ^6.0.1
  firebase_auth: ^6.0.2
  firebase_messaging: ^16.0.1
  firebase_storage: ^13.0.1
  firebase_analytics: ^12.0.1
  firebase_data_connect: ^0.2.0+2

  # Local storage
  hive_ce: ^2.11.3
  hive_ce_flutter: ^2.3.2
  shared_preferences: ^2.3.2

  # UI & routing
  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter

  # Notifications & background work (requires Flutter ≥3.22)
  flutter_local_notifications: ^19.4.1
  workmanager: ^0.9.0+3

  # Utilities
  json_annotation: ^4.9.0
  intl: ^0.20.2
  uuid: ^4.5.1
  equatable: ^2.0.5
  freezed_annotation: ^3.1.0

  # HTTP clients
  http: ^1.2.2
  dio: ^5.7.0

  # Permissions, timezone & logging
  permission_handler: ^12.0.1
  timezone: ^0.10.1
  logger: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  # Code generation toolchain – these versions require Dart ≥3.7/3.8
  build_runner: ^2.6.1         # Uses build 3.x; min SDK 3.7
  json_serializable: ^6.11.0   # Dart ≥3.8 required
  freezed: ^3.2.0              # Dart ≥3.8
  hive_ce_generator: ^1.9.3    # Compatible with analyzer 7
  mockito: ^5.5.0              # Dart ≥3.7

  # Static analysis
  flutter_lints: ^6.0.0




# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
