default_platform(:ios)

platform :ios do
  desc "Build IPA"
  lane :build do
    build_app(scheme: "Runner")
  end

  desc "Upload to TestFlight"
  lane :beta do
    build_app(scheme: "Runner")
    upload_to_testflight
  end
end

