type User @table {
  displayName: String!
  email: String!
  role: String!
  createdAt: Timestamp!
  photoUrl: String
  groupHome: GroupHome
}

type GroupHome @table {
  name: String!
  adminUser: User!
  createdAt: Timestamp!
  description: String
  address: String
}

type Task @table {
  groupHome: GroupHome!
  title: String!
  description: String!
  assignedToUser: User!
  dueDate: Timestamp!
  status: String!
  type: String!
  createdAt: Timestamp!
  recurrence: String
  completedByUser: User
  completedAt: Timestamp
}

type GroceryItem @table {
  groupHome: GroupHome!
  name: String!
  addedByUser: User!
  status: String!
  createdAt: Timestamp!
  quantity: Int
  notes: String
  purchasedByUser: User
  purchasedAt: Timestamp
}

type Notification @table {
  user: User!
  message: String!
  type: String!
  read: Boolean!
  createdAt: Timestamp!
  relatedTask: Task
  relatedGroceryItem: GroceryItem
}