// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:house_organizer/data/models/audit_log.dart';
import 'package:house_organizer/data/models/house.dart';
import 'package:house_organizer/data/models/list_item.dart';
import 'package:house_organizer/data/models/list_model.dart';
import 'package:house_organizer/data/models/task.dart';
import 'package:house_organizer/data/models/user.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AuditLogAdapter());
    registerAdapter(HouseAdapter());
    registerAdapter(ListItemAdapter());
    registerAdapter(ListModelAdapter());
    registerAdapter(TaskAdapter());
    registerAdapter(UserAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AuditLogAdapter());
    registerAdapter(HouseAdapter());
    registerAdapter(ListItemAdapter());
    registerAdapter(ListModelAdapter());
    registerAdapter(TaskAdapter());
    registerAdapter(UserAdapter());
  }
}
