// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4D3z0tIoAyYlLsYt7IH2SOmZxj0oAnR8',
    appId: '1:996807597018:web:845e7d94389fd0f731bee3',
    messagingSenderId: '996807597018',
    projectId: 'house-organizer-75193',
    authDomain: 'house-organizer-75193.firebaseapp.com',
    storageBucket: 'house-organizer-75193.firebasestorage.app',
    measurementId: 'G-24JZF7L0X4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDm_kdENCiynPIn9zdVgPbzVEgwe9M1xk8',
    appId: '1:996807597018:android:181a6362238e37ca31bee3',
    messagingSenderId: '996807597018',
    projectId: 'house-organizer-75193',
    storageBucket: 'house-organizer-75193.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhD69A1s-vhoqzGKWwdbtJUGJ47hL1xwg',
    appId: '1:996807597018:ios:5f370a1ead87346631bee3',
    messagingSenderId: '996807597018',
    projectId: 'house-organizer-75193',
    storageBucket: 'house-organizer-75193.firebasestorage.app',
    iosBundleId: 'com.grouphome.organizer.houseOrganizer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhD69A1s-vhoqzGKWwdbtJUGJ47hL1xwg',
    appId: '1:996807597018:ios:5f370a1ead87346631bee3',
    messagingSenderId: '996807597018',
    projectId: 'house-organizer-75193',
    storageBucket: 'house-organizer-75193.firebasestorage.app',
    iosBundleId: 'com.grouphome.organizer.houseOrganizer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4D3z0tIoAyYlLsYt7IH2SOmZxj0oAnR8',
    appId: '1:996807597018:web:a3ba5d6e94780d7331bee3',
    messagingSenderId: '996807597018',
    projectId: 'house-organizer-75193',
    authDomain: 'house-organizer-75193.firebaseapp.com',
    storageBucket: 'house-organizer-75193.firebasestorage.app',
    measurementId: 'G-7SZ9TEQD9G',
  );
}
