name: Flutter CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: house_organizer
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'
      - name: Flutter Pub Get
        run: flutter pub get
      - name: Analyze
        run: flutter analyze
      - name: Run Tests
        run: flutter test --no-pub

  build-android:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push'
    defaults:
      run:
        working-directory: house_organizer
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'
      - name: Flutter Pub Get
        run: flutter pub get
      - name: Build Android AppBundle
        run: flutter build appbundle --release --no-pub

  build-ios:
    runs-on: macos-latest
    needs: test
    if: github.event_name == 'push'
    defaults:
      run:
        working-directory: house_organizer
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'
      - name: Flutter Pub Get
        run: flutter pub get
      - name: Build iOS
        run: |
          flutter build ipa --release --no-pub || true
        env:
          CI: true

